name: Build and Release

on:
  push:
    tags:
      - 'v[0-9]+.*'


jobs:
  build-and-release:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
          
      - name: Install dependencies
        run: go mod tidy
        
      - name: Build binary
        run: go build -o uex ./cmd/uex
        
      - name: Upload artifacts to existing release
        uses: ncipollo/release-action@v1
        with:
          artifacts: uex
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}