name: Build and Release

on:
  push:
    tags:
      - 'v[0-9]+.*'
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install dependencies
        run: go mod tidy

      - name: Build binary
        run: go build -o uex ./cmd/uex

      - name: Upload build artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: uex-binary
          path: ./uex

  release:
    name: Release
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: uex-binary

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: uex
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Automated release for version ${{ github.ref_name }}.